#!/bin/bash
# A.TT.I.L.A. Terraform GCS Backend Initializer
# "Noi sbabbari, prima rademo al suolo e poi discutiamo!" 🗡️

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <PROJECT_ID> [REGION]"
  exit 1
fi

PROJECT_ID="$1"
REGION="${2:-europe-west1}"
BUCKET_NAME="${PROJECT_ID}-attila-tfstate"

echo "===================================================="
echo "🗡️  Initializing Terraform GCS Backend..."
echo "    Project: $PROJECT_ID"
echo "    Region:  $REGION"
echo "    Bucket:  gs://$BUCKET_NAME"
echo "===================================================="

# Check if bucket exists
if gsutil ls -b "gs://$BUCKET_NAME" >/dev/null 2>&1; then
  echo "[+] GCS Bucket gs://$BUCKET_NAME already exists."
else
  echo "[+] GCS Bucket gs://$BUCKET_NAME does not exist. Creating it..."
  gsutil mb -p "$PROJECT_ID" -l "$REGION" "gs://$BUCKET_NAME"
  echo "[+] Enabling object versioning on the bucket..."
  gsutil versioning set on "gs://$BUCKET_NAME"
fi

# Generate backend.tf dynamically
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_FILE="$SCRIPT_DIR/backend.tf"

echo "[+] Generating backend.tf..."
cat <<EOF > "$BACKEND_FILE"
# Generated by 00_init.sh. Do not edit manually.
terraform {
  backend "gcs" {
    bucket = "$BUCKET_NAME"
    prefix = "terraform/state"
  }
}
EOF

echo "[+] Initializing Terraform..."
cd "$SCRIPT_DIR"
terraform init

echo "===================================================="
echo "[+] Terraform GCS Backend initialized successfully!"
echo "===================================================="
