#!/bin/bash
# A.TT.I.L.A. Terraform GCS Backend Initializer
# "Noi sbabbari, prima rademo al suolo e poi discutiamo!" 🗡️

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

# 1. Load and validate .env configuration
if [ ! -f "$ENV_FILE" ]; then
  echo "[-] ERROR: .env file not found at $ENV_FILE."
  echo "    Please run 'just init <PROJECT_ID>' first to generate the configuration."
  exit 1
fi

# Helper function to read env variables safely
get_env_var() {
  grep -E "^$1=" "$ENV_FILE" | cut -d= -f2 | tr -d '"'\'' '
}

PROJECT_ID=$(get_env_var "PROJECT_ID")
GCP_IDENTITY=$(get_env_var "GCP_IDENTITY")
REGION="europe-west1" # Default region

if [ -z "$PROJECT_ID" ]; then
  echo "[-] ERROR: PROJECT_ID is not defined in your .env file."
  exit 1
fi

if [ -z "$GCP_IDENTITY" ]; then
  echo "[-] ERROR: GCP_IDENTITY is not defined in your .env file."
  exit 1
fi

# 2. Enforce active gcloud identity matches GCP_IDENTITY
echo "[+] Verifying active gcloud identity..."
ACTIVE_IDENTITY=$(gcloud config get-value account 2>/dev/null || echo "")

if [ -z "$ACTIVE_IDENTITY" ]; then
  echo "[-] ERROR: You are not authenticated with gcloud. Please run 'gcloud auth login'."
  exit 1
fi

if [ "$ACTIVE_IDENTITY" != "$GCP_IDENTITY" ]; then
  echo "[-] ERROR: Identity mismatch!"
  echo "    Active gcloud account: $ACTIVE_IDENTITY"
  echo "    Required .env account: $GCP_IDENTITY"
  echo "    Please switch account: 'gcloud config set account $GCP_IDENTITY'"
  exit 1
fi

BUCKET_NAME="${PROJECT_ID}-attila-tfstate"

echo "===================================================="
echo "🗡️  Initializing Terraform GCS Backend..."
echo "    Project:  $PROJECT_ID"
echo "    Identity: $GCP_IDENTITY"
echo "    Region:   $REGION"
echo "    Bucket:   gs://$BUCKET_NAME"
echo "===================================================="

# Check if bucket exists
if gsutil ls -b "gs://$BUCKET_NAME" >/dev/null 2>&1; then
  echo "[+] GCS Bucket gs://$BUCKET_NAME already exists."
else
  echo "[+] GCS Bucket gs://$BUCKET_NAME does not exist. Creating it..."
  gsutil mb -p "$PROJECT_ID" -l "$REGION" "gs://$BUCKET_NAME"
  echo "[+] Enabling object versioning on the bucket..."
  gsutil versioning set on "gs://$BUCKET_NAME"
fi

# Generate backend.tf dynamically
BACKEND_FILE="$SCRIPT_DIR/backend.tf"
echo "[+] Generating backend.tf..."
cat <<EOF > "$BACKEND_FILE"
# Generated by 00_init.sh. Do not edit manually.
terraform {
  backend "gcs" {
    bucket = "$BUCKET_NAME"
    prefix = "terraform/state"
  }
}
EOF

echo "[+] Initializing Terraform..."
cd "$SCRIPT_DIR"
terraform init

echo "===================================================="
echo "[+] Terraform GCS Backend initialized successfully!"
echo "===================================================="
